print("Everyone loves Mad libs")
user=input("Enter your name:")
print("Welcome", user)
print("Let's play!")
adj=input("enter an adjective: ")
noun=input("enter a noun: ")
ptv=input("enter past-tense verb: ")
noun2=input("enter another noun: ")
print("The quick", adj, noun, ptv, "over the lazy", noun2)
print("That was FUN!")
print("Let's do another one.")
verb=input("enter a verb: ")
noun3=input("enter a noun:")
noun4=input("enter another noun:")
print("If you can", verb, "a", noun3, "you can", verb, "a", noun4,"!")
print("adapted from the movie, Dodgeball")